version: "3"
services:
  web:
    build: ./api
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    environment:
      API_PORT_D: $API_PORT
      API_PING_D: $API_PING
    ports:
      - "4000:80"
